
[package]
authors = ["himanoa <matsunoappy@gmail.com>"]
edition = "2018"
name = "example"
version = "0.1.1"
license = "MIT"
homepage = "https://github.com/himanoa/mkrepo"
repository = "https://github.com/himanoa/mkrepo"
keywords = ["cli", "ghq"]
categories = ["command-line-utilities"]
readme="README.md"
description = "Create repository directory for ghq style"
[[bin]]
name = "example"
path = "src/main.rs"
[dependencies]
